## Finals Task 5.
                                   
Instructions: 

1. To have an idea of how SQL views work, kindly read the lecture on SQL views and stored procedures, then you may try the following examples in MySQL Workbench: 
2. Start Xampp and MySQL Workbench – create or start a connection 
4. Open the democodes.sql, and you may try executing all the examples using the hrd.sql file

5. AFTER the practice codes…. Perform the required SQL statements of the ff: use inventory.sql for this.

6. Print screen the appropriate sql and output per item

Task 1 CREATE A VIEW that will display the vendors_code, vendors name, product description p_indate, of all products with p_indate from 2002 onwards

Task 2 CREATE a VIEW that will display all products whose price range is between 100-150

Task 3 Create a VIEW that will COMPUTE for the (TOTAL_PRICE) of ALL PRODUCTS by getting the (P_ONHAND x P_PRICE) Sold by vendors with the following v_code (21344, 23119 and 24288)


Task 4 CREATE a STORED PROCEDURE that WILL take a SINGLE PARAMETER and UPDATED the Name of Vendor ‘Bryson,Inc.’ to ‘Bryson and Co’.


Task 5 CREATE A Function that will take 2 parameters(v_code and v_state) and display All the product description and price based on the parameters passed to the function

## QUERY STATEMENTS

TASK 1
![1QUERY](https://github.com/user-attachments/assets/a9ce44b0-b17a-4771-887e-5ba79e71d0f3)

TASK 2
![2QUERY](https://github.com/user-attachments/assets/dd9f07bb-e9cf-4fc4-b6b9-88618ef928b8)

TASK 3
![3QUERY](https://github.com/user-attachments/assets/66c69cef-6a18-4dfd-9efc-a8c7e064236f)

TASK 4
![4QUERIES](https://github.com/user-attachments/assets/05ed79df-7e66-4ee7-841d-29fc499aa332)

TASK 5
![5QUERIES](https://github.com/user-attachments/assets/0af8c05d-2ef9-4171-9a24-55953ccbec59)

## TABLES

TASK 1
![1TABLE](https://github.com/user-attachments/assets/5f224f78-f287-47ff-a2ab-233089635fb6)

TASK 2
![2TABLE](https://github.com/user-attachments/assets/49af3e5d-4c7a-417f-88dd-6d8ee96238d3)

TASK 3
![3TABLE](https://github.com/user-attachments/assets/03b9d43f-b7f7-4209-a160-ac8a5455d2bf)

TASK 4
![4TABLE](https://github.com/user-attachments/assets/117af159-c0b0-4529-bf69-ffaa77997173)

TASK 5
![5TABLE](https://github.com/user-attachments/assets/174346a9-fade-4325-b6a3-ebcd09a48a2a)
